process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const { PrismaClient } = require('../app/generated/prisma');
const { PrismaPg } = require('@prisma/adapter-pg');
const pg = require('pg');
require('dotenv').config();

const pool = new pg.Pool({
  connectionString: process.env.DIRECT_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({
  adapter,
});

async function main() {
  console.log('Clearing existing data...');
  await prisma.project.deleteMany({});
  await prisma.experience.deleteMany({});
  await prisma.category.deleteMany({});

  console.log('Seeding categories...');
  const catAnalytics = await prisma.category.create({
    data: { name: 'Analytics Pipelines', slug: 'analytics-pipelines' }
  });
  const catDashboards = await prisma.category.create({
    data: { name: 'Business Intelligence', slug: 'bi' }
  });

  console.log('Seeding projects...');
  await prisma.project.create({
    data: {
      title: 'E-commerce Cohort Retention Engine',
      slug: 'ecommerce-cohort-retention-engine',
      description: 'An automated Python and SQL analytics system that extracts raw transaction logs and calculates rolling customer retention metrics.',
      problem: 'The marketing team had no clear insight into customer lifecycle values. They could not distinguish between one-time shoppers and high-value repeat customers.',
      solution: 'Developed an automated ELT pipeline using Python and PostgreSQL. Implemented SQL window functions and common table expressions (CTEs) to group customers into weekly purchase cohorts.',
      results: 'Uncovered that 80% of repeat revenue is generated by cohorts acquired during seasonal discount windows. Optimized marketing allocation, reducing acquisition cost by 25%.',
      techStack: ['Python', 'PostgreSQL', 'Pandas', 'Matplotlib'],
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop',
      githubUrl: 'https://github.com/sandranzekwe/cohort-retention',
      liveUrl: null,
      featured: true,
      dataSource: 'Raw CSV transactional logs containing 500k+ rows representing two years of e-commerce purchases.',
      analysis: 'Calculated month-over-month retention matrix, customer lifetime value (CLV), and repeat purchase probability curves.',
      visualizations: 'Built heatmaps showing retention degradation curves over time and cohort purchase frequencies.',
      outcome: 'Presented visual slide decks directly to the VP of Marketing, highlighting low-retention segments and suggesting targeted email win-back campaigns.',
      businessImpact: 'Re-allocated $50k in advertising spend to high-value cohorts, increasing secondary-month retention rates by 12%.',
      categories: { connect: [{ id: catAnalytics.id }] }
    }
  });

  await prisma.project.create({
    data: {
      title: 'SaaS Interactive Finance Dashboard',
      slug: 'saas-interactive-finance-dashboard',
      description: 'A comprehensive Power BI executive reporting suite showing real-time MRR, LTV, churn rate, and operational overhead metrics.',
      problem: 'Executive leaders spent 5+ hours preparing metrics slide decks before weekly meetings, pulling from separate Stripe, HubSpot, and QuickBooks CSVs.',
      solution: 'Engineered a unified SQL Server database schema to house cleaned metrics, and connected it to Power BI. Authored advanced DAX measures to calculate MRR changes, cohort churn, and pipeline efficiency.',
      results: 'Automated 100% of executive weekly reporting, reducing preparation time to zero and providing real-time data visibility to investors.',
      techStack: ['Power BI', 'SQL Server', 'DAX', 'Power Query'],
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop',
      githubUrl: null,
      liveUrl: 'https://powerbi.microsoft.com',
      featured: true,
      dataSource: 'Stripe transaction APIs, HubSpot sales pipeline records, and QuickBooks accounting tables.',
      analysis: 'Calculated monthly recurring revenue (MRR) expansion, contraction, and churn. Modeled customer acquisition cost (CAC) payback periods.',
      visualizations: 'Engineered clean cards, waterfall charts showing MRR changes, and line plots of cohort lifespan decay.',
      outcome: 'Delivered an interactive reporting portal embedded directly in the company’s internal intranet with automated daily refreshes.',
      businessImpact: 'Provided immediate visibility into a 4% spike in customer churn, prompting rapid customer success interventions.',
      categories: { connect: [{ id: catDashboards.id }] }
    }
  });

  await prisma.project.create({
    data: {
      title: 'Supply Chain Operations Pipeline',
      slug: 'supply-chain-operations-pipeline',
      description: 'A Python ETL script automating shipment transit delay forecasting and database loading routines.',
      problem: 'Operations managers had to manually query multiple freight carrier websites to find delivery delays, leading to delayed warehouse staffing plans.',
      solution: 'Wrote python web scraping and API ingestion scripts. Built an automated cleaning routine to standardize timestamps and coordinates into a PostgreSQL database.',
      results: 'Created a central repository showing delay patterns, allowing warehouse teams to optimize staffing schedules based on shipment estimates.',
      techStack: ['Python', 'PostgreSQL', 'APIs', 'Docker'],
      image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=600&auto=format&fit=crop',
      githubUrl: 'https://github.com/sandranzekwe/supply-chain-etl',
      liveUrl: null,
      featured: false,
      dataSource: 'XML and JSON endpoints from DHL, FedEx, and UPS carrier portals.',
      analysis: 'Conducted travel time averages per route, carrier latency metrics, and variance analysis.',
      visualizations: 'Built map-based delay plots showing regional shipping bottleneck coordinates.',
      outcome: 'Set up cron jobs running on a local server to push cleaned tables to database daily.',
      businessImpact: 'Reduced warehouse worker idle time by 18%, saving approximately $4k in labor costs monthly.',
      categories: { connect: [{ id: catAnalytics.id }] }
    }
  });

  console.log('Seeding experiences...');
  await prisma.experience.create({
    data: {
      role: 'Junior Data Analyst',
      company: 'Apex Logistics Analytics',
      duration: '2024 - Present',
      description: 'Own SQL queries and reporting suites. Build and automate dashboard updates, analyze carrier transit times, and write python cleaning scripts for carrier transaction records.'
    }
  });

  await prisma.experience.create({
    data: {
      role: 'Project Coordinator',
      company: 'Vanguard Civil Construction Ltd',
      duration: '2021 - 2023',
      description: 'Managed materials inventory databases, coordinated subcontractor delivery timelines in Excel, and analyzed budget variances to reduce materials waste.'
    }
  });

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await pool.end();
  });
