import React from "react";
import { ExternalLink, Database, Cpu, TrendingUp, BarChart2 } from "lucide-react";
import prisma from "../lib/prisma";
import Footer from "../components/footer";

const GithubIcon = ({ className = "w-4 h-4" }: { className?: string }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
    <path d="M9 18c-4.51 2-5-2-7-2" />
  </svg>
);

export const revalidate = 60; // Revalidate every minute

async function getProjects() {
  try {
    const projects = await prisma.project.findMany({
      include: {
        categories: true
      },
      orderBy: {
        createdAt: 'desc'
      }
    });
    return projects;
  } catch (error) {
    console.error("Error fetching projects:", error);
    return [];
  }
}

export default async function Projects() {
  const dbProjects = await getProjects();

  // Fallbacks if database is empty
  const fallbackProjects = [
    {
      id: "demo-1",
      title: "E-commerce Cohort Retention Engine",
      slug: "ecommerce-cohort-retention-engine",
      description: "An automated Python and SQL analytics system that extracts raw transaction logs and calculates rolling customer retention metrics.",
      problem: "The marketing team had no clear insight into customer lifecycle values. They could not distinguish between one-time shoppers and high-value repeat customers.",
      solution: "Developed an automated ELT pipeline using Python and PostgreSQL. Implemented SQL window functions and common table expressions (CTEs) to group customers into weekly purchase cohorts.",
      results: "Uncovered that 80% of repeat revenue is generated by cohorts acquired during seasonal discount windows. Optimized marketing allocation, reducing acquisition cost by 25%.",
      techStack: ["Python", "PostgreSQL", "Pandas", "Matplotlib"],
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop",
      githubUrl: "https://github.com/sandranzekwe/cohort-retention",
      liveUrl: null,
      featured: true,
      dataSource: "Raw CSV transactional logs containing 500k+ rows representing two years of e-commerce purchases.",
      analysis: "Calculated month-over-month retention matrix, customer lifetime value (CLV), and repeat purchase probability curves.",
      visualizations: "Built heatmaps showing retention degradation curves over time and cohort purchase frequencies.",
      businessImpact: "Re-allocated $50k in advertising spend to high-value cohorts, increasing secondary-month retention rates by 12%.",
      categories: [{ name: "Analytics Pipelines" }]
    },
    {
      id: "demo-2",
      title: "SaaS Interactive Finance Dashboard",
      slug: "saas-interactive-finance-dashboard",
      description: "A comprehensive Power BI executive reporting suite showing real-time MRR, LTV, churn rate, and operational overhead metrics.",
      problem: "Executive leaders spent 5+ hours preparing metrics slide decks before weekly meetings, pulling from separate Stripe, HubSpot, and QuickBooks CSVs.",
      solution: "Engineered a unified SQL Server database schema to house cleaned metrics, and connected it to Power BI. Authored advanced DAX measures to calculate MRR changes, cohort churn, and pipeline efficiency.",
      results: "Automated 100% of executive weekly reporting, reducing preparation time to zero and providing real-time data visibility to investors.",
      techStack: ["Power BI", "SQL Server", "DAX", "Power Query"],
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
      githubUrl: null,
      liveUrl: "https://powerbi.microsoft.com",
      featured: true,
      dataSource: "Stripe transaction APIs, HubSpot sales pipeline records, and QuickBooks accounting tables.",
      analysis: "Calculated monthly recurring revenue (MRR) expansion, contraction, and churn. Modeled customer acquisition cost (CAC) payback periods.",
      visualizations: "Engineered clean cards, waterfall charts showing MRR changes, and line plots of cohort lifespan decay.",
      businessImpact: "Provided immediate visibility into a 4% spike in customer churn, prompting rapid customer success interventions.",
      categories: [{ name: "Business Intelligence" }]
    }
  ];

  const projects = dbProjects.length > 0 ? dbProjects : fallbackProjects;

  return (
    <div className="flex flex-col min-h-screen bg-zinc-50 dark:bg-[#09090b] text-zinc-900 dark:text-zinc-50 relative">
      <main className="flex-grow pt-28 pb-16">
        {/* Glow ambient background lights */}
        <div className="absolute top-1/4 left-10 w-96 h-96 bg-purple-500/10 rounded-full blur-[128px] pointer-events-none" />
        <div className="absolute bottom-1/3 right-10 w-96 h-96 bg-blue-500/10 rounded-full blur-[128px] pointer-events-none" />

        <div className="max-w-5xl mx-auto px-6 py-12 relative z-10">
          <div className="text-center max-w-xl mx-auto mb-16">
            <span className="text-xs font-bold uppercase tracking-wider text-purple-600 dark:text-purple-400 bg-purple-500/10 px-3 py-1 rounded-full">
              Portfolio
            </span>
            <h1 className="text-4xl md:text-5xl font-black tracking-tight mt-3 text-zinc-950 dark:text-white">
              Data Case Studies
            </h1>
            <p className="text-xs sm:text-sm text-zinc-500 dark:text-zinc-400 mt-2">
              Explores end-to-end data architectures, analytical methods, statistical calculations, and business insights.
            </p>
          </div>

          <div className="flex flex-col gap-20">
            {projects.map((project: any) => (
              <section
                key={project.id}
                id={project.slug}
                className="scroll-mt-32 p-6 md:p-8 rounded-3xl bg-white dark:bg-zinc-900/40 border border-zinc-200 dark:border-white/5 shadow-md flex flex-col gap-8"
              >
                {/* Header info */}
                <div className="grid md:grid-cols-12 gap-8 items-center">
                  <div className="md:col-span-7 flex flex-col gap-4">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-purple-600 dark:text-purple-400 bg-purple-500/10 px-3 py-1 rounded-full border border-purple-500/5">
                        {project.categories?.[0]?.name || "Analytics"}
                      </span>
                    </div>
                    <h2 className="text-2xl md:text-3xl font-black tracking-tight text-zinc-950 dark:text-white leading-tight">
                      {project.title}
                    </h2>
                    <p className="text-xs sm:text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed">
                      {project.description}
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {project.techStack.map((tech: string, idx: number) => (
                        <span key={idx} className="text-[10px] font-semibold tracking-wide uppercase px-2.5 py-1 bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 rounded-lg">
                          {tech}
                        </span>
                      ))}
                    </div>
                  </div>
                  
                  {/* Aspect ratio preview image */}
                  <div className="md:col-span-5 relative aspect-video rounded-2xl overflow-hidden border border-zinc-200 dark:border-white/5 bg-zinc-950 shadow-sm">
                    <img
                      src={project.image}
                      alt={project.title}
                      className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-500"
                    />
                  </div>
                </div>

                <hr className="border-zinc-200 dark:border-white/5" />

                {/* Case Study Details grid */}
                <div className="grid md:grid-cols-3 gap-6">
                  {/* Left block Problem/Solution/Results */}
                  <div className="md:col-span-2 flex flex-col gap-6">
                    <div className="flex flex-col gap-2">
                      <h4 className="text-xs font-bold uppercase tracking-widest text-purple-600 dark:text-purple-400 flex items-center gap-1.5">
                        <Cpu className="w-4 h-4" />
                        The Problem
                      </h4>
                      <p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
                        {project.problem}
                      </p>
                    </div>

                    <div className="flex flex-col gap-2">
                      <h4 className="text-xs font-bold uppercase tracking-widest text-purple-600 dark:text-purple-400 flex items-center gap-1.5">
                        <Database className="w-4 h-4" />
                        The Solution
                      </h4>
                      <p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
                        {project.solution}
                      </p>
                    </div>

                    <div className="flex flex-col gap-2">
                      <h4 className="text-xs font-bold uppercase tracking-widest text-purple-600 dark:text-purple-400 flex items-center gap-1.5">
                        <TrendingUp className="w-4 h-4" />
                        Analysis & Calculations
                      </h4>
                      <p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
                        {project.analysis}
                      </p>
                    </div>
                  </div>

                  {/* Right block Data Source/Visuals/Impact */}
                  <div className="p-5 rounded-2xl bg-zinc-100/50 dark:bg-zinc-900/60 border border-zinc-200/50 dark:border-white/5 flex flex-col gap-6">
                    <div className="flex flex-col gap-1.5">
                      <h5 className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Data Source</h5>
                      <p className="text-xs text-zinc-600 dark:text-zinc-300">{project.dataSource}</p>
                    </div>

                    <div className="flex flex-col gap-1.5">
                      <h5 className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Visualizations</h5>
                      <p className="text-xs text-zinc-600 dark:text-zinc-300">{project.visualizations}</p>
                    </div>

                    <div className="flex flex-col gap-1.5">
                      <h5 className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider">Business Impact</h5>
                      <p className="text-xs font-semibold text-purple-600 dark:text-purple-400">{project.businessImpact}</p>
                    </div>
                    
                    <div className="flex gap-3 mt-2">
                      {project.githubUrl && (
                        <a
                          href={project.githubUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="flex-grow inline-flex items-center justify-center gap-2 py-2.5 rounded-xl border border-zinc-200 dark:border-white/10 bg-white dark:bg-zinc-950 text-xs font-bold text-zinc-700 dark:text-zinc-300 hover:text-purple-600 dark:hover:text-white transition-all shadow-sm"
                        >
                          <GithubIcon className="w-4 h-4" />
                          Codebase
                        </a>
                      )}
                      {project.liveUrl && (
                        <a
                          href={project.liveUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="flex-grow inline-flex items-center justify-center gap-2 py-2.5 rounded-xl bg-purple-600 text-white text-xs font-bold hover:bg-purple-700 transition-all shadow-md shadow-purple-500/10"
                        >
                          <ExternalLink className="w-4 h-4" />
                          View Live
                        </a>
                      )}
                    </div>
                  </div>
                </div>
              </section>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
